# test
name: Terraform Deployment
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./s3.bucket

    steps:

      - uses: actions/checkout@v4

      - name: Get OIDC Token
        id: oidc
        run: |
         TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
           "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=vault" | jq -r '.value')
   
         echo "$TOKEN" | cut -d "." -f2 | base64 -d | jq . 
         
      - name: Fetch Keys from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://3.108.41.99:8200
          role: gh-actions-role
          method: jwt
          secrets: |
            aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY

      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve